name:                mtg
version:             0.1.1.0
github:              "SimonBarkehanai/mtg"
license:             BSD-3-Clause
author:              "Simon Barkehanai"
maintainer:          "simonxob@gmail.com"
copyright:           "2024 Simon Barkehanai"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SimonBarkehanai/mtg#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- case-insensitive
- containers
- directory
- filepath
- http-client
- http-client-tls
- optparse-applicative
- text
- time
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

_exe-common: &exe-common 
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - mtg

executables:
  search:
    <<: *exe-common
    main:                Search.hs
    source-dirs:         app/search
  download-images:
    <<: *exe-common
    main:                DownloadImages.hs
    source-dirs:         app/download-img
  download-tokens:
    <<: *exe-common
    main:                DownloadTokens.hs
    source-dirs:         app/download-tok
  log-downloader:
    <<: *exe-common
    main:                LogDownloader.hs
    source-dirs:         app/log-downloader

tests:
  mtg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtg
